### ISSUE TITLE
Settings options should be more descriptive

### ISSUE THREAD

**Issue by krnekhelesh** [rschroll/gmail-scope#10]
Currently there are 2 settings options with a checkbox "Thread messages" and "Show message snippets", it would be nice if you could use a listitem.subtitled where you can provide some description as to what these settings do.

Initially I was guessing does the "Thread messages" shows message thread in the email view or in the main scope page or not...and adding more detail would help clarify this.

**Comment by rschroll** [comment]
The settings need some clean up.  See also #7.

Unfortunately, I don't think there's any way to have more than a single 
line of text associated with each option.  If I'm wrong, please correct 
me.

**Comment by krnekhelesh** [comment]
I do not have any experience with what can be done with scopes, so I trust your word on that ;). That said, it seems like the scope customization is quite restrictive on how much you can change its appearance.

**Comment by rschroll** [comment]
Because of #7, I'm changing this to be a drop-down menu with three 
choices.  My current wording is to title the menu "View messages..." 
and the choices "In threads", "Individually", and "Individually with 
snippets".  Does this strike you as clear?  Do you have another 
suggestion?

**Comment by rschroll** [comment]
I've pushed a fix to #7 that changes the wording here.  I think this is 
enough, so I'm closing this bug.  But if you still find it less than 
clear, please say so.
