### ISSUE TITLE
Days are getting cutoff in the email list

### ISSUE THREAD

**Issue by krnekhelesh** [rschroll/gmail-scope#11]
As you can see in the screenshot below, the days like **Wednesday** has the first letter cut of. 

![gmailscope](https://cloud.githubusercontent.com/assets/761845/5117957/83bf7892-705b-11e4-8603-cecaff488f2e.png)

**Comment by rschroll** [comment]
You've found an ugly corner of the code.  There's no way that I've 
found to put text over there, so the date markers are actually images.  
I've widened them a bit so that Wednesday will fit in.  Ideally we'll 
get an option to put text in this position.
